# Generated by Django 2.1.10 on 2019-10-08 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationTaskItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_source_phrase_id', models.IntegerField()),
                ('_target_phrase_id', models.IntegerField(null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='translationtask',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='translationtaskitem',
            name='translation_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.TranslationTask'),
        ),
    ]
