# Generated by Django 2.1.10 on 2019-10-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20191008_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationtaskitem',
            name='_phrases_shared_id',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
