# Generated by Django 2.1.10 on 2019-10-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_translationtaskitem__phrases_shared_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationtaskitem',
            name='_source_phrase_id',
        ),
        migrations.RemoveField(
            model_name='translationtaskitem',
            name='_target_phrase_id',
        ),
        migrations.AlterField(
            model_name='translationtaskitem',
            name='_phrases_shared_id',
            field=models.UUIDField(),
        ),
    ]
