# Generated by Django 2.1.10 on 2019-10-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20191010_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationtask',
            name='total_word_count',
            field=models.IntegerField(default=None),
        ),
    ]
