# Generated by Django 2.1.10 on 2019-10-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('accounts', '0003_auto_20191007_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='languages',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='languages',
            field=models.ManyToManyField(related_name='user_profile_set', related_query_name='user_profile_set', to='store.Language'),
        ),
    ]
